use std::fs;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Deserializer, Serialize};
use thiserror::Error;

use crate::ui::theme::{PartialThemeConfig, ThemeConfig};

pub const CONFIG_ENV_VAR: &str = "BRUTUI_CONFIG";

/// The annotated template written by `brutui init`.
/// Every supported key is shown, commented out, with its built-in default
/// noted inline so users know what they are overriding.
pub const INIT_CONFIG_TEMPLATE: &str = r#"# brutui configuration — generated by `brutui init`
# All keys are optional. Uncomment and edit the ones you need.
# Override this file's location with the BRUTUI_CONFIG environment variable.

# ── Collections ──────────────────────────────────────────────────────────────
# Directories to scan for Bruno collections on startup.
# Each entry may be a collection root itself or a parent directory containing
# multiple roots. Brutui recognises roots that contain bruno.json or
# opencollection.yml.
#
# collection_dirs = [
#   "/path/to/your/collections",
# ]

# ── Bruno executable ─────────────────────────────────────────────────────────
# Explicit path to the `bru` CLI binary.
# Resolution order: BRUTUI_BRU_PATH env var → bru_path below → bru on PATH.
#
# bru_path = "/opt/homebrew/bin/bru"

# ── Theme ────────────────────────────────────────────────────────────────────
# Each section controls one UI style slot. All fields within each section are
# optional — omit a field to keep its built-in default.
#
# Colors accept named terminal colors:
#   black, red, green, yellow, blue, magenta, cyan, gray, dark_gray,
#   light_red, light_green, light_yellow, light_blue, light_magenta,
#   light_cyan, white
# or an RGB hex value in #RRGGBB format.

# Base style applied to all content not otherwise styled.
# [theme.base]
# fg =          # default: terminal default
# bg =          # default: terminal default
# bold = false
# italic = false
# underlined = false
# reversed = false
# dim = false

# Border of an unfocused panel.
# [theme.panel_border]
# fg = "dark_gray"  # default
# bg =          # default: terminal default
# bold = false
# italic = false
# underlined = false
# reversed = false
# dim = false

# Border of the currently focused panel.
# [theme.focused_panel_border]
# fg = "cyan" # default
# bg =          # default: terminal default
# bold = false
# italic = false
# underlined = false
# reversed = false
# dim = false

# A highlighted item in an unfocused list.
# [theme.selected_item]
# fg =           # default: terminal default
# bg =           # default: terminal default
# bold = false
# italic = false
# underlined = false
# reversed = true  # default
# dim = false

# A highlighted item in the focused list.
# [theme.focused_selected_item]
# fg =           # default: terminal default
# bg =           # default: terminal default
# bold = true    # default
# italic = false
# underlined = false
# reversed = true  # default
# dim = false

# Text given extra visual prominence (headings, labels, etc.).
# [theme.emphasized_text]
# fg =           # default: terminal default
# bg =           # default: terminal default
# bold = true    # default
# italic = false
# underlined = false
# reversed = false
# dim = false
"#;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Default)]
pub struct AppConfig {
    #[serde(default)]
    pub collection_dirs: Vec<PathBuf>,
    pub bru_path: Option<PathBuf>,
    pub theme: ThemeConfig,
}

#[derive(Debug, Deserialize)]
struct RawAppConfig {
    #[serde(default)]
    collection_dirs: Vec<PathBuf>,
    bru_path: Option<PathBuf>,
    #[serde(default)]
    theme: PartialThemeConfig,
}

impl<'de> Deserialize<'de> for AppConfig {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let raw = RawAppConfig::deserialize(deserializer)?;
        Ok(Self {
            collection_dirs: raw.collection_dirs,
            bru_path: raw.bru_path,
            theme: ThemeConfig::default().merge(raw.theme),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LoadedConfig {
    pub path: Option<PathBuf>,
    pub config: AppConfig,
}

#[derive(Debug, Error)]
pub enum InitError {
    #[error(
        "could not determine a config directory for this system; \
        set {env_var} to an explicit path and re-run"
    )]
    NoConfigDir { env_var: &'static str },

    #[error(
        "config file already exists at {path}; \
        remove it manually if you want to regenerate it"
    )]
    AlreadyExists { path: PathBuf },

    #[error("failed to create config directory {path}: {source}")]
    CreateDir {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },

    #[error("failed to write config file {path}: {source}")]
    Write {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
}

/// Write [`INIT_CONFIG_TEMPLATE`] to [`default_config_path()`] and print the
/// path and file contents to stdout.
///
/// Returns an error if the path cannot be determined, the file already exists,
/// the parent directory cannot be created, or the write fails.
pub fn init() -> Result<(), InitError> {
    let path = default_config_path().ok_or(InitError::NoConfigDir {
        env_var: CONFIG_ENV_VAR,
    })?;

    if path.exists() {
        return Err(InitError::AlreadyExists { path });
    }

    if let Some(parent) = path.parent() {
        if !parent.exists() {
            fs::create_dir_all(parent).map_err(|source| InitError::CreateDir {
                path: parent.to_path_buf(),
                source,
            })?;
        }
    }

    fs::write(&path, INIT_CONFIG_TEMPLATE).map_err(|source| InitError::Write {
        path: path.clone(),
        source,
    })?;

    println!("Created {}", path.display());

    Ok(())
}

#[derive(Debug, Error)]
pub enum ConfigError {
    #[error("config override {path} from {env_var} does not exist")]
    ConfigOverrideNotFound {
        env_var: &'static str,
        path: PathBuf,
    },
    #[error("failed to read config file {path}: {source}")]
    Read {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("failed to parse config file {path}: {source}")]
    Parse {
        path: PathBuf,
        #[source]
        source: toml::de::Error,
    },
    #[error("configured collection directory {path} does not exist or is not a directory")]
    InvalidCollectionDir { path: PathBuf },
    #[error("configured bru executable {path} does not exist or is not a file")]
    InvalidBruPath { path: PathBuf },
}

pub fn default_config_path() -> Option<PathBuf> {
    directories::BaseDirs::new()
        .map(|dirs| dirs.home_dir().join(".config").join("brutui").join("config.toml"))
}

pub fn resolved_config_path() -> Option<PathBuf> {
    std::env::var_os(CONFIG_ENV_VAR)
        .filter(|value| !value.is_empty())
        .map(PathBuf::from)
        .or_else(default_config_path)
}

pub fn load() -> Result<LoadedConfig, ConfigError> {
    if let Some(path) = std::env::var_os(CONFIG_ENV_VAR)
        .filter(|value| !value.is_empty())
        .map(PathBuf::from)
    {
        if !path.exists() {
            return Err(ConfigError::ConfigOverrideNotFound {
                env_var: CONFIG_ENV_VAR,
                path,
            });
        }

        return load_from_path(&path).map(|config| LoadedConfig {
            path: Some(path),
            config,
        });
    }

    let Some(path) = default_config_path() else {
        return Ok(LoadedConfig {
            path: None,
            config: AppConfig::default(),
        });
    };

    if !path.exists() {
        return Ok(LoadedConfig {
            path: Some(path),
            config: AppConfig::default(),
        });
    }

    load_from_path(&path).map(|config| LoadedConfig {
        path: Some(path),
        config,
    })
}

pub fn load_from_path(path: impl AsRef<Path>) -> Result<AppConfig, ConfigError> {
    let path = path.as_ref();
    let contents = fs::read_to_string(path).map_err(|source| ConfigError::Read {
        path: path.to_path_buf(),
        source,
    })?;
    let mut config: AppConfig = toml::from_str(&contents).map_err(|source| ConfigError::Parse {
        path: path.to_path_buf(),
        source,
    })?;
    let base_dir = path.parent().unwrap_or_else(|| Path::new("."));

    config.collection_dirs = config
        .collection_dirs
        .into_iter()
        .map(|dir| normalize_existing_dir(base_dir, &dir))
        .collect::<Result<Vec<_>, _>>()?;
    config.bru_path = config
        .bru_path
        .map(|path| normalize_existing_file(base_dir, &path))
        .transpose()?;

    Ok(config)
}

fn normalize_existing_dir(base_dir: &Path, path: &Path) -> Result<PathBuf, ConfigError> {
    let absolute = absolutize(base_dir, path);
    let normalized = absolute
        .canonicalize()
        .map_err(|_| ConfigError::InvalidCollectionDir {
            path: absolute.clone(),
        })?;

    if normalized.is_dir() {
        Ok(normalized)
    } else {
        Err(ConfigError::InvalidCollectionDir { path: normalized })
    }
}

fn normalize_existing_file(base_dir: &Path, path: &Path) -> Result<PathBuf, ConfigError> {
    let absolute = absolutize(base_dir, path);
    let normalized = absolute
        .canonicalize()
        .map_err(|_| ConfigError::InvalidBruPath {
            path: absolute.clone(),
        })?;

    if normalized.is_file() {
        Ok(normalized)
    } else {
        Err(ConfigError::InvalidBruPath { path: normalized })
    }
}

fn absolutize(base_dir: &Path, path: &Path) -> PathBuf {
    if path.is_absolute() {
        path.to_path_buf()
    } else {
        base_dir.join(path)
    }
}
